[tool.ruff]
line-length = 100
target-version = "py310"
extend-select = ["I", "B", "C", "F", "E", "W"]
ignore = ["E501"]  # disabilita lunghezza linea se vuoi

[tool.ruff.lint]
fixable = ["ALL"]
